version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:80"
    env_file:
      - .env.local # Default to local, change as needed
    environment:
      - NAME=TTS_API
  # mysql_db:
  #   image: mysql:8.4.0
  #   env_file:
  #     - .env.local # Default to local, change as needed
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   ports:
  #     - "3306:3306"
